# Generated by Django 6.1.1 on 2026-09-15 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Software / Chatbot')),
                ('endpoint', models.CharField(max_length=500, verbose_name='Endpoint URL / WebSocket')),
                ('protocol', models.CharField(choices=[('HTTP/HTTPS', 'HTTP/HTTPS'), ('WebSocket', 'WebSocket'), ('STT/Audio', 'STT/Audio')], default='HTTP/HTTPS', max_length=20, verbose_name='Protocolo')),
                ('llm_provider', models.CharField(max_length=100, verbose_name='Proveedor / Modelo LLM')),
                ('system_prompt_sample', models.TextField(blank=True, null=True, verbose_name='Muestra de System Prompt')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Mapeando', 'Mapeando')], default='Activo', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrador')),
            ],
            options={
                'verbose_name': 'Software Objetivo',
                'verbose_name_plural': 'Softwares Objetivos',
                'ordering': ['-created_at'],
            },
        ),
    ]
