# Generated by Django 6.1.1 on 2026-09-13 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms',
            field=models.BooleanField(default=False, help_text='Indica si el usuario aceptó los Términos y Condiciones'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario Pentester que creó este usuario (para Auditores)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Indica si la cuenta fue activada por el Administrador del Sistema'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'Administrador del Sistema'), ('PENTESTER', 'Pentester'), ('AUDITOR', 'Auditor')], default='PENTESTER', help_text='Rol asignado al usuario en GenAI Security Lab', max_length=20),
        ),
    ]
