# Generated by Django 6.1.1 on 2026-09-15 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('tiempo', models.CharField(help_text="Duración del plan (ej. '30 días', '1 mes', '1 año')", max_length=50, verbose_name='Tiempo de Duración')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Tarifa')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto ($ USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoletaSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boleta', models.CharField(max_length=50, unique=True, verbose_name='Número de Boleta')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pentester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas_suscripcion', to=settings.AUTH_USER_MODEL, verbose_name='Pentester Titular')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='monetizacion.plan', verbose_name='Plan Suscrito')),
            ],
            options={
                'verbose_name': 'Boleta de Suscripción',
                'verbose_name_plural': 'Boletas de Suscripción',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='tarifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='monetizacion.tarifa', verbose_name='Tarifa Asociada'),
        ),
    ]
