# Generated by Django 6.1.1 on 2026-09-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetizacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='tiempo',
        ),
        migrations.AddField(
            model_name='plan',
            name='duracion_dias',
            field=models.PositiveIntegerField(default=30, help_text='Duración del plan en días (ej. 30 para 1 mes, 365 para 1 año)', verbose_name='Duración en Días'),
        ),
    ]
