# Generated by Django 5.2.17 on 2026-09-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetizacion', '0003_insert_plan_gratuito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletasuscripcion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
